apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 001329948138.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 001329948138.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: e046042f
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
